練習課題4「Google検索ページ」
codeschoolway/j-kadai-04 pull request #1
Opened 2020-03-03 00:10 UTC by codeschoolway

# 内容
初回の提出物

2020-03-03 05:24 UTC, fjtawork reviewed
講師の藤田です。

もし`.gitignore`というのを知っていたら、それを使って
.DS_Storeなどの無関係なファイルをコミットから外しましょう！

まだ習っていなければ、このままで問題ないと思います。

2020-03-03 05:24 UTC, fjtawork commented on index.html
> +                <div id="logo-g"></div>
これは不要なdivですかね？中身に要素がないので。

2020-03-03 10:59 UTC, codeschoolway commented
> もし`.gitignore`というのを知っていたら、それを使って
> .DS_Storeなどの無関係なファイルをコミットから外しましょう！

今後対応します。

2020-03-03 11:02 UTC, codeschoolway commented on index.html
> +                <div id="logo-g"></div>
Googleのロゴを`background-image`で挿入しました。`img`で作った方が良いでしょうか。

2020-03-04 02:46 UTC, yusaku-inamura commented on index.html
> +                <div id="logo-g"></div>
cssで表示すべきかimg要素として配置すべきかの線引きは確定でこれ！といった決まりは無いのですが大雑把に説明すると `ページ内の装飾かそうでないか(コンテンツ上必要な要素か)` という観点で判断します。

企業やサービスのロゴ画像に関してはブランディング上必須(こういったロゴ画像というのはwebページ作成時に最も意識して扱う必要がある画像)のため、img要素でいいと思います。

2020-03-04 08:09 UTC, codeschoolway commented on index.html
> +                <div id="logo-g"></div>
img要素に変更しました。

2020-03-04 08:25 UTC, yusaku-inamura commented on .gitignore
> +.DS_Store
`.gitignore` 使って管理不要なファイルを除外できているのとてもいいですね 👍 
ただ実はすでにcommitされてしまっているファイルには効かないのです 😢 

ちょっと発展的な内容になってしまいますが、せっかく `.gitignore` 追加していただいてますので、git管理下から除外するコマンドを使ってみましょう!

`git rm --cached {削除したいファイル名}`

上記のコマンドで削除可能です。
`{削除したいファイル名}` の部分は適当なものに適宜置き換えてください。
例えば `css/.DS_Store` を削除したい場合は `git rm --cached css/.DS_Store` ですね。

2020-03-04 08:25 UTC, yusaku-inamura commented on index.html
> +                <div id="logo-g"></div>
確認しました 🙆‍♂

2020-03-04 08:28 UTC, yusaku-inamura requested changes
質問いただいていた内容については修正確認しました 👍 
個別でコメントさせていただいていますが、折角ですのでgitignoreが機能するようにgitからファイルを削除するコマンドを試してみてください。

2020-03-05 09:37 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-03-05 09:37 UTC, piasoratech commented on index.html
> +    <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"> -->
コメントアウトしたものはプルリクエストに含めないようにしましょう。

2020-03-05 09:37 UTC, piasoratech commented on index.html
> +        <header>
`header`タグが一番外に来るように修正しましょう。

2020-03-05 10:38 UTC, codeschoolway commented on index.html
> +        <header>
`header`タグはコンテンツ全体を包んでいる`<div class="wrapper">`の子要素となっていますがこのdivより外に配置するということでしょうか。

2020-03-05 10:55 UTC, codeschoolway commented on index.html
> +    <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"> -->
修正しました。

2020-03-05 11:05 UTC, piasoratech commented on index.html
> +        <header>
その通りです。
headerタグは親要素にできるタグが限られており、divタグはheaderタグを子要素として扱うことができません。
下記のURLも参考にしてください。
https://developer.mozilla.org/ja/docs/Web/HTML/Element/header

2020-03-19 08:50 UTC, nozomi71 commented on index.html
> +                </li>
ここ、左右でブロック分けたほうがいいですね

2020-03-19 08:50 UTC, nozomi71 commented on css/style.css
> +    padding-left: 50px;
入力欄の内側も余白ほしいですね

2020-03-19 08:50 UTC, nozomi71 commented on css/style.css
> +    border: 1px solid #f2f2f2;
ボーダーの色一緒ならわざわざボーダーで取る必要ないです
padding当てるなどして高さや幅調整しましょう！

2020-03-19 08:50 UTC, nozomi71 commented on css/style.css
> +    position: absolute;
ここabsolute使いません〜

2020-03-19 08:50 UTC, nozomi71 commented on index.html
> +            <li><a href="#">設定</a></li>
ここも左右でブロック分けましょう

2020-03-19 09:22 UTC, codeschoolway commented on index.html
> +                </li>
修正しました。

2020-03-19 09:22 UTC, codeschoolway commented on css/style.css
> +    padding-left: 50px;
修正しました。

2020-03-19 09:22 UTC, codeschoolway commented on css/style.css
> +    border: 1px solid #f2f2f2;
修正しました。

2020-03-19 09:23 UTC, codeschoolway commented on css/style.css
> +    position: absolute;
# 質問
absoluteを外すと`footer`が上に移動してしまいます。他の方法を使うべきということでしょうか。

<img width="1792" alt="2020-03-19 18 14 33" src="https://user-images.githubusercontent.com/61524044/77050995-f1149b00-6a0d-11ea-9e9e-509a809ac84e.png">

2020-03-19 09:24 UTC, codeschoolway commented on index.html
> +            <li><a href="#">設定</a></li>
修正しました。

2020-03-19 15:57 UTC, codeschoolway commented on css/style.css
> +    border: 1px solid #f2f2f2;
`border: 1px solid #f2f2f2`が無いとボタンがずれてしまいます。

無し
![20200319214241](https://user-images.githubusercontent.com/61524044/77086600-56d04980-6a45-11ea-9fe8-220278e0d8c2.gif)

あり
![20200319214725-1](https://user-images.githubusercontent.com/61524044/77086625-5e8fee00-6a45-11ea-9d20-5bd90427accc.gif)

2020-03-19 16:13 UTC, codeschoolway commented on css/style.css
> +    padding-left: 50px;
修正前ですが内側の余白はこれで十分かもしれません。入力文字が小さくなってしまうかも。
<img width="659" alt="スクリーンショット 2020-03-20 1 08 30" src="https://user-images.githubusercontent.com/61524044/77088179-6c467300-6a47-11ea-9c01-a183f10e1139.png">

2020-03-25 02:37 UTC, nozomi71 commented on css/style.css
> +    padding-left: 50px;
左右に、という意味ですね
現状のままだと文字を入力欄いっぱいに入力したとき、右側がボーダーぎりぎりになってしまいます

2020-03-25 02:38 UTC, nozomi71 commented on css/style.css
> +    position: absolute;
`min-heigth`指定しましょう

2020-03-25 02:43 UTC, nozomi71 commented on css/style.css
> +    border: 1px solid #f2f2f2;
あ〜hoverの指定してるんですね…
そこまで求めないのでhoverの指定しなくてOKです

2020-03-25 02:44 UTC, nozomi71 commented on css/style.css
> +    border: 1px solid #f2f2f2;
この現象は、ずれるのではなく、hover時に1px分ボックスが大きくなるために起こっています
これを防ぐには堀内さんがされたようにnot hover時に同じ色のボーダーを当てるか、ボックスにサイズ指定を行います

2020-03-25 03:46 UTC, codeschoolway commented on css/style.css
> +    position: absolute;
html ファイルでコンテンツ全体を<div class="wrp">で囲む
footerのpotisionとbottomを削除

2020-03-25 04:00 UTC, codeschoolway commented on css/style.css
> +    padding-left: 50px;
なるほど！修正しました。

2020-03-25 04:00 UTC, codeschoolway commented on css/style.css
> +    border: 1px solid #f2f2f2;
修正しました。

2020-03-25 04:09 UTC, codeschoolway commented on css/style.css
> +    position: absolute;
HTMLファイル：
13行目：コンテンツ全体を`div class="wrp"で`囲む

CSSファイル：
91行目：`footer`のpotisionとbottomを削除
114行目：`.wrp`を指定

2020-03-25 06:51 UTC, nozomi71 commented on css/style.css
> +    min-width: 100vw;
これいらないです〜

2020-03-25 06:51 UTC, nozomi71 commented on css/style.css
> +    margin-top: auto;
こうするよりmainに`min-height`あてたいですね

2020-03-25 07:33 UTC, codeschoolway commented on css/style.css
> +    min-width: 100vw;
修正しました。

2020-03-25 07:38 UTC, codeschoolway commented on css/style.css
> +    margin-top: auto;
当初は`main`に`min-height: 100vh`を当てたのですが`header`と`footer`の高さ分が画面の外に出てしまったため他の方法にしました。

`header`
`main`← min-height: 100vh;
`footer`

今回は`main`に
`min-height: calc(100vh - 231px);`
を当てました。 `header`と `footer`の高さを引きました。画面のサイズを変えても`header`から`footer`まで表示されてますがどうでしょう・・・。

2020-03-25 07:59 UTC, nozomi71 commented on css/style.css
> +    margin-top: auto;
その修正で正解です！

2020-03-25 08:02 UTC, umurajim approved these changes
良いかと〜！

2020-03-25 08:43 UTC, merged